### ISSUE TITLE
Colors not supported

### ISSUE THREAD

**Issue by stesvis** [impe93/react-native-wind#48]
Hello,
I am enjoying this package! However I was wondering which colors are not supported?

The documentation references to this [Tailwindcss link](https://tailwindcss.com/docs/customizing-colors) for possible colors, but I was trying to use the `slate` variants and they are not applying. For example `text-slate-200` just displays plain black.

I also tried to grab all the colors codes and customize the theme like this, unsuccessfully:
```js
import { customize } from "react-native-wind";

customize({
  theme: {
    colors: {
      slate: {
        50: "#f8fafc",
        100: "#f1f5f9",
        200: "#e2e8f0",
        300: "#cbd5e1",
        400: "#94a3b8",
        500: "#64748b",
        600: "#475569",
        700: "#334155",
        800: "#1e293b",
        900: "#0f172a",
      },
    },
  },
});
```
Again, `text-slate-200` just displays plain black.

Please advise if there is some config that I need to add maybe? thank you!

**Comment by impe93** [comment]
Hi @stesvis! I'm sorry, my bad! The link was added last year but the tailwind doc has changed! Anyway slate colors are not supported out of the box but through customizations as you did, but I think that you miss a small thing! 😁

As is stated [in the customization guide](https://reactnativewind.com/docs/core/customization) (almost at the end of the page), when customized classes are used you have to import `wind.config.ts` file at the start of your index.js file like this:

```typescript
import './wind.config';
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

Let me know if this solve your problem 🙂

**Comment by stesvis** [comment]
Thanks @impe93 I am using expo and I don't have an `index.js` but only an `App.js`.
However I did it like this:
```jsx
import "./wind.config";
import AppInfo from "./app.json";

// ...

export default function App() {
    // ...
}

AppRegistry.registerComponent(AppInfo.expo.name, () => App);

And it seems to be working!

I had another question, is positioning supported? I mean absolute positioning, with top/bottom/left/right properties?
https://tailwindcss.com/docs/position

**Comment by impe93** [comment]
Yes is working! You can find all available classes [on the documentation](https://reactnativewind.com/docs/utilities/layout/top-bottom-left-right). If you find some problem on it, please, open another issue! I'm going to close this one 🙂
