### ISSUE TITLE
Customize default font size

### ISSUE THREAD

**Issue by stesvis** [impe93/react-native-wind#49]
Hello, me again, is it possible to customize the font size in `wind.config.js`?

Something on the line of:
```js
customize({
  theme: {
    fontSize: {
        // what here??
    }
  }
});
```

If possible could you provide an example or link to one? Basically I would like to customize all the font-sizes to be 1px bigger.

**Comment by impe93** [comment]
Hey @stesvis! At the moment isn't possible but should be easy to develop, I'm going to label this issue as a feature request 🙂

**Comment by stesvis** [comment]
> Hey @stesvis! At the moment isn't possible but should be easy to develop, I'm going to label this issue as a feature request 🙂
> 
> I'm in search of contributors, so if you are interested feel free to open a PR 😁

Sounds good! I was asked to make the font a little bigger and I would prefer not to have to customize every component if there is a way to do it globally by overriding the defaults.

Not to put any pressure on you haha, but when do you think it could be available?
Again, appreciate your work. I was using another package with many more tailwindss features, but it has too many bugs.

I prefer something smaller, but working :)

**Comment by impe93** [comment]
I don't suggest overriding the default values, anyway, I think I can do it over the weekend 😁

**Comment by stesvis** [comment]
That would be fantastic! Complimenti!

**Comment by stesvis** [comment]
@impe93 did you have any luck with it?
Would you suggest any workaround?

**Comment by impe93** [comment]
Hi @stesvis! I've merged the feature that you requested 🙂 You just need to upgrade to version 1.2.0 ! It's now possible to customize the font size in this way:
```typescript
customize({
  fontSize: {
    // Your custom font size name
    customSize: {
      fontSize: 31 // Your size here
    }
  }
})
```
Now it's possible to use the class `text-customSize` that would set the font-size to 31.

Let me know if there are some problems.

**Comment by stesvis** [comment]
Thank you @impe93 ! Can I add as many as I want, or does it need to be called `customSize`?

1) Can I add more, like this?

```js
customize({
  fontSize: {
    // Your custom font size name
    customSizeSm: {
      fontSize: 12
    },
    customSizeBase: {
      fontSize: 14
    },
    customSizeLg: {
      fontSize: 18
    },
  }
})
```

2) Can I also define the `lineHeight`?

3) Can you override the defaults ones? So if in my code I used `text-lg` or `text-sm` in several places, does this change allow you to re-set those sizes and apply automatically?

**Comment by impe93** [comment]
1. You can call the classes as you want, "customSize" was just an example because I had no ideas about the name lol.
2. It is possible to define the `lineHeight` within the same object.
3. You can override the defaults but I usually don't suggest doing it 🙂

**Comment by stesvis** [comment]
Fantastic, thank you very much.
Scusa devo chiedertelo, sei italiano vero?

**Comment by impe93** [comment]
Awesome! Open an Issue if you find some bug ;)

Anyway yes! I'm Italian, from Turin! To avoid going off-topic you can PM me on Linkedin, [this is my profile](https://www.linkedin.com/in/lorenzo-imperatrice/).
